### ISSUE TITLE
Specify license, please

### ISSUE THREAD

**Issue by tjormola** [geowarin/graphql-webflux#1]
Hello!

This sure looks seriously cool and interesting, thank you! I was going to write something really similar, but this does the trick. However, I can't just take things as is since it's missing license. Would you mind specifying the license for this code (Apache or BSD hopefully)?

**Comment by geowarin** [comment]
Fixed in bc7b2db.
It is under MIT license. Does it fit the bill for you ?

**Comment by tjormola** [comment]
Sure, it's great, thanks ;)
